module.exports = [
	require( 'pure-button' ),
	// require( 'pure-icon' ),
	// require( 'pure-spinner' ),
	// require( 'pure-pagination' ),
	// require( 'pure-breadcrumb' ),
	// require( 'pure-breadcrumb-item' ),
	// require( 'pure-tabs' ),
	// require( 'pure-tab-pane' ),
	// require( 'pure-input' ),
	// require( 'pure-textarea' ),
	// require( 'pure-radio' ),
	// require( 'pure-radio-button' ),
	// require( 'pure-radio-group' ),
	// require( 'pure-checkbox' ),
	// require( 'pure-checkbox-group' ),
	// require( 'pure-select' ),
	// require( 'pure-option' ),
	// require( 'pure-switch' ),
	// require( 'pure-modal' ),
	// require( 'pure-box' ),
	// require( 'pure-note' ),
	// require( 'pure-countdown' ),
];
